### ISSUE TITLE
Fails to install CocoaPods dependencies

### ISSUE THREAD

**Issue by heades** [rescript-react-native/rescript-react-native#795]
## The problem

Running the new application initialization command:

```
npx @react-native-community/cli init --template @rescript-react-native/template MyApp
cd MyApp
```

Fails to properly setup the iOS environment:

```
✔ Downloading template
✔ Copying template
✔ Processing template
ℹ Executing post init script 
You are now ready to use ReScript React Native. Be sure to check the docs at https://rescript-react-native.github.io/
✖ Installing CocoaPods dependencies (this may take a few minutes)
error Could not locate Gemfile or .bundle/ directory

✖ Installing CocoaPods dependencies (this may take a few minutes)
error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
Error: Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
    at createFromTemplate (.../.npm/_npx/14345/lib/node_modules/@react-native-community/cli/build/commands/init/init.js:131:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.initialize [as func] (.../.npm/_npx/14345/lib/node_modules/@react-native-community/cli/build/commands/init/init.js:184:3)
    at async Command.handleAction (.../.npm/_npx/14345/lib/node_modules/@react-native-community/cli/build/index.js:106:9)
```

### How to reproduce

Steps to reproduce:

1. Run the command:
   ```
   npx @react-native-community/cli init --template @rescript-react-native/template MyApp
   cd MyApp
   ```
   on mac OS X.

## Expected behavior

A completely setup app.

## Actual behavior

Fails to properly setup the iOS environment:

```
✔ Downloading template
✔ Copying template
✔ Processing template
ℹ Executing post init script 
You are now ready to use ReScript React Native. Be sure to check the docs at https://rescript-react-native.github.io/
✖ Installing CocoaPods dependencies (this may take a few minutes)
error Could not locate Gemfile or .bundle/ directory

✖ Installing CocoaPods dependencies (this may take a few minutes)
error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
Error: Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
    at createFromTemplate (.../.npm/_npx/14345/lib/node_modules/@react-native-community/cli/build/commands/init/init.js:131:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.initialize [as func] (.../.npm/_npx/14345/lib/node_modules/@react-native-community/cli/build/commands/init/init.js:184:3)
    at async Command.handleAction (.../.npm/_npx/14345/lib/node_modules/@react-native-community/cli/build/index.js:106:9)
```

## Environment

- Mac OS X 13.2.1
- npm/npx 6.14.15

**Comment by heades** [comment]
I'm closing this, because it was due to the template using an old version of RN.  I upgraded it, and now it's building the app.
