### ISSUE TITLE
Unable to resolve module `belt_Option.js`

### ISSUE THREAD

**Issue by heades** [rescript-react-native/rescript-react-native#796]
## The problem

When building the template using commands:

```
> npx @react-native-community/cli init --template @rescript-react-native/template myApp
> cd myApp
> npm run ios
```

The following error is reported:

```
error: Error: Unable to resolve module rescript/lib/es6/belt_Option.js from /Users/heades/development/YTJ/src/App.bs.js: rescript/lib/es6/belt_Option.js could not be found within the project or in these directories:
  node_modules
  2 |
  3 | import * as React from "react";
> 4 | import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
    |                               ^
  5 | import * as Caml_option from "rescript/lib/es6/caml_option.js";
  6 | import * as ReactNative from "react-native";
  7 | import * as ReactNativeHelloWorldUtils from "./ReactNativeHelloWorldUtils.bs.js";
    at ModuleResolver.resolveDependency (/Users/heades/development/YTJ/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:162:15)
    at DependencyGraph.resolveDependency (/Users/heades/development/YTJ/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/Users/heades/development/YTJ/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/Users/heades/development/YTJ/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/Users/heades/development/YTJ/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at async Graph._addDependency (/Users/heades/development/YTJ/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 0)
    at async Graph._processModule (/Users/heades/development/YTJ/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
    at async Graph._addDependency (/Users/heades/development/YTJ/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 2)
```

### How to reproduce

Steps to reproduce:

Run the commands:

```
> npx @react-native-community/cli init --template @rescript-react-native/template myApp
> cd myApp
> npm run ios
```

## Expected behavior

The app to build and run without errors.

## Actual behavior

We get an error, see above.

## Environment

info Fetching system and libraries information...
System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 626.36 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.7.0 - ~/.nvm/versions/node/v19.7.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v19.7.0/bin/npm
    Watchman: 2023.02.27.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 30
      System Images: android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

I have rescript: 10.1.2

**Comment by heades** [comment]
Closing this as I've realized that the template is outdated and stale, so I'll just start with a latest RN project, and convert it manually.
